//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace SmokeNote.Client.Models
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class financepersonalEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“financepersonalEntities”部分中的连接字符串初始化新 financepersonalEntities 对象。
        /// </summary>
        public financepersonalEntities() : base("name=financepersonalEntities", "financepersonalEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 financepersonalEntities 对象。
        /// </summary>
        public financepersonalEntities(string connectionString) : base(connectionString, "financepersonalEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 financepersonalEntities 对象。
        /// </summary>
        public financepersonalEntities(EntityConnection connection) : base(connection, "financepersonalEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<acount> acount
        {
            get
            {
                if ((_acount == null))
                {
                    _acount = base.CreateObjectSet<acount>("acount");
                }
                return _acount;
            }
        }
        private ObjectSet<acount> _acount;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<action> action
        {
            get
            {
                if ((_action == null))
                {
                    _action = base.CreateObjectSet<action>("action");
                }
                return _action;
            }
        }
        private ObjectSet<action> _action;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<role> role
        {
            get
            {
                if ((_role == null))
                {
                    _role = base.CreateObjectSet<role>("role");
                }
                return _role;
            }
        }
        private ObjectSet<role> _role;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<user> user
        {
            get
            {
                if ((_user == null))
                {
                    _user = base.CreateObjectSet<user>("user");
                }
                return _user;
            }
        }
        private ObjectSet<user> _user;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 用于向 acount EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToacount(acount acount)
        {
            base.AddObject("acount", acount);
        }
    
        /// <summary>
        /// 用于向 action EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToaction(action action)
        {
            base.AddObject("action", action);
        }
    
        /// <summary>
        /// 用于向 role EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTorole(role role)
        {
            base.AddObject("role", role);
        }
    
        /// <summary>
        /// 用于向 user EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTouser(user user)
        {
            base.AddObject("user", user);
        }

        #endregion
    }
    

    #endregion
    
    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="financepersonalModel", Name="acount")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class acount : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 acount 对象。
        /// </summary>
        /// <param name="acountId">AcountId 属性的初始值。</param>
        public static acount Createacount(global::System.Int32 acountId)
        {
            acount acount = new acount();
            acount.AcountId = acountId;
            return acount;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AcountId
        {
            get
            {
                return _AcountId;
            }
            set
            {
                if (_AcountId != value)
                {
                    OnAcountIdChanging(value);
                    ReportPropertyChanging("AcountId");
                    _AcountId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AcountId");
                    OnAcountIdChanged();
                }
            }
        }
        private global::System.Int32 _AcountId;
        partial void OnAcountIdChanging(global::System.Int32 value);
        partial void OnAcountIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AcountUserId
        {
            get
            {
                return _AcountUserId;
            }
            set
            {
                OnAcountUserIdChanging(value);
                ReportPropertyChanging("AcountUserId");
                _AcountUserId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AcountUserId");
                OnAcountUserIdChanged();
            }
        }
        private global::System.String _AcountUserId;
        partial void OnAcountUserIdChanging(global::System.String value);
        partial void OnAcountUserIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AcountTotal
        {
            get
            {
                return _AcountTotal;
            }
            set
            {
                OnAcountTotalChanging(value);
                ReportPropertyChanging("AcountTotal");
                _AcountTotal = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AcountTotal");
                OnAcountTotalChanged();
            }
        }
        private global::System.String _AcountTotal;
        partial void OnAcountTotalChanging(global::System.String value);
        partial void OnAcountTotalChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AcountDefine1
        {
            get
            {
                return _AcountDefine1;
            }
            set
            {
                OnAcountDefine1Changing(value);
                ReportPropertyChanging("AcountDefine1");
                _AcountDefine1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AcountDefine1");
                OnAcountDefine1Changed();
            }
        }
        private global::System.String _AcountDefine1;
        partial void OnAcountDefine1Changing(global::System.String value);
        partial void OnAcountDefine1Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AcountDefine2
        {
            get
            {
                return _AcountDefine2;
            }
            set
            {
                OnAcountDefine2Changing(value);
                ReportPropertyChanging("AcountDefine2");
                _AcountDefine2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AcountDefine2");
                OnAcountDefine2Changed();
            }
        }
        private global::System.String _AcountDefine2;
        partial void OnAcountDefine2Changing(global::System.String value);
        partial void OnAcountDefine2Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AcountDefine3
        {
            get
            {
                return _AcountDefine3;
            }
            set
            {
                OnAcountDefine3Changing(value);
                ReportPropertyChanging("AcountDefine3");
                _AcountDefine3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AcountDefine3");
                OnAcountDefine3Changed();
            }
        }
        private global::System.String _AcountDefine3;
        partial void OnAcountDefine3Changing(global::System.String value);
        partial void OnAcountDefine3Changed();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="financepersonalModel", Name="action")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class action : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 action 对象。
        /// </summary>
        /// <param name="actionId">ActionId 属性的初始值。</param>
        public static action Createaction(global::System.Int32 actionId)
        {
            action action = new action();
            action.ActionId = actionId;
            return action;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ActionId
        {
            get
            {
                return _ActionId;
            }
            set
            {
                if (_ActionId != value)
                {
                    OnActionIdChanging(value);
                    ReportPropertyChanging("ActionId");
                    _ActionId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ActionId");
                    OnActionIdChanged();
                }
            }
        }
        private global::System.Int32 _ActionId;
        partial void OnActionIdChanging(global::System.Int32 value);
        partial void OnActionIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ActionCountId
        {
            get
            {
                return _ActionCountId;
            }
            set
            {
                OnActionCountIdChanging(value);
                ReportPropertyChanging("ActionCountId");
                _ActionCountId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ActionCountId");
                OnActionCountIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ActionCountId;
        partial void OnActionCountIdChanging(Nullable<global::System.Int32> value);
        partial void OnActionCountIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ActionUserId
        {
            get
            {
                return _ActionUserId;
            }
            set
            {
                OnActionUserIdChanging(value);
                ReportPropertyChanging("ActionUserId");
                _ActionUserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ActionUserId");
                OnActionUserIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ActionUserId;
        partial void OnActionUserIdChanging(Nullable<global::System.Int32> value);
        partial void OnActionUserIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ActionName
        {
            get
            {
                return _ActionName;
            }
            set
            {
                OnActionNameChanging(value);
                ReportPropertyChanging("ActionName");
                _ActionName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ActionName");
                OnActionNameChanged();
            }
        }
        private global::System.String _ActionName;
        partial void OnActionNameChanging(global::System.String value);
        partial void OnActionNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ActionMoney
        {
            get
            {
                return _ActionMoney;
            }
            set
            {
                OnActionMoneyChanging(value);
                ReportPropertyChanging("ActionMoney");
                _ActionMoney = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ActionMoney");
                OnActionMoneyChanged();
            }
        }
        private global::System.String _ActionMoney;
        partial void OnActionMoneyChanging(global::System.String value);
        partial void OnActionMoneyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ActionRole
        {
            get
            {
                return _ActionRole;
            }
            set
            {
                OnActionRoleChanging(value);
                ReportPropertyChanging("ActionRole");
                _ActionRole = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ActionRole");
                OnActionRoleChanged();
            }
        }
        private global::System.String _ActionRole;
        partial void OnActionRoleChanging(global::System.String value);
        partial void OnActionRoleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ActionCommet
        {
            get
            {
                return _ActionCommet;
            }
            set
            {
                OnActionCommetChanging(value);
                ReportPropertyChanging("ActionCommet");
                _ActionCommet = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ActionCommet");
                OnActionCommetChanged();
            }
        }
        private global::System.String _ActionCommet;
        partial void OnActionCommetChanging(global::System.String value);
        partial void OnActionCommetChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ActionTime
        {
            get
            {
                return _ActionTime;
            }
            set
            {
                OnActionTimeChanging(value);
                ReportPropertyChanging("ActionTime");
                _ActionTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ActionTime");
                OnActionTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _ActionTime;
        partial void OnActionTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnActionTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ActionDefine1
        {
            get
            {
                return _ActionDefine1;
            }
            set
            {
                OnActionDefine1Changing(value);
                ReportPropertyChanging("ActionDefine1");
                _ActionDefine1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ActionDefine1");
                OnActionDefine1Changed();
            }
        }
        private global::System.String _ActionDefine1;
        partial void OnActionDefine1Changing(global::System.String value);
        partial void OnActionDefine1Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ActionDefine2
        {
            get
            {
                return _ActionDefine2;
            }
            set
            {
                OnActionDefine2Changing(value);
                ReportPropertyChanging("ActionDefine2");
                _ActionDefine2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ActionDefine2");
                OnActionDefine2Changed();
            }
        }
        private global::System.String _ActionDefine2;
        partial void OnActionDefine2Changing(global::System.String value);
        partial void OnActionDefine2Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ActionDefine3
        {
            get
            {
                return _ActionDefine3;
            }
            set
            {
                OnActionDefine3Changing(value);
                ReportPropertyChanging("ActionDefine3");
                _ActionDefine3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ActionDefine3");
                OnActionDefine3Changed();
            }
        }
        private global::System.String _ActionDefine3;
        partial void OnActionDefine3Changing(global::System.String value);
        partial void OnActionDefine3Changed();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="financepersonalModel", Name="role")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class role : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 role 对象。
        /// </summary>
        /// <param name="roleId">RoleId 属性的初始值。</param>
        public static role Createrole(global::System.Int32 roleId)
        {
            role role = new role();
            role.RoleId = roleId;
            return role;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RoleId
        {
            get
            {
                return _RoleId;
            }
            set
            {
                if (_RoleId != value)
                {
                    OnRoleIdChanging(value);
                    ReportPropertyChanging("RoleId");
                    _RoleId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RoleId");
                    OnRoleIdChanged();
                }
            }
        }
        private global::System.Int32 _RoleId;
        partial void OnRoleIdChanging(global::System.Int32 value);
        partial void OnRoleIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RoleName
        {
            get
            {
                return _RoleName;
            }
            set
            {
                OnRoleNameChanging(value);
                ReportPropertyChanging("RoleName");
                _RoleName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RoleName");
                OnRoleNameChanged();
            }
        }
        private global::System.String _RoleName;
        partial void OnRoleNameChanging(global::System.String value);
        partial void OnRoleNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RoleAttr
        {
            get
            {
                return _RoleAttr;
            }
            set
            {
                OnRoleAttrChanging(value);
                ReportPropertyChanging("RoleAttr");
                _RoleAttr = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RoleAttr");
                OnRoleAttrChanged();
            }
        }
        private global::System.String _RoleAttr;
        partial void OnRoleAttrChanging(global::System.String value);
        partial void OnRoleAttrChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RoleDefine1
        {
            get
            {
                return _RoleDefine1;
            }
            set
            {
                OnRoleDefine1Changing(value);
                ReportPropertyChanging("RoleDefine1");
                _RoleDefine1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RoleDefine1");
                OnRoleDefine1Changed();
            }
        }
        private global::System.String _RoleDefine1;
        partial void OnRoleDefine1Changing(global::System.String value);
        partial void OnRoleDefine1Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RoleDefine2
        {
            get
            {
                return _RoleDefine2;
            }
            set
            {
                OnRoleDefine2Changing(value);
                ReportPropertyChanging("RoleDefine2");
                _RoleDefine2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RoleDefine2");
                OnRoleDefine2Changed();
            }
        }
        private global::System.String _RoleDefine2;
        partial void OnRoleDefine2Changing(global::System.String value);
        partial void OnRoleDefine2Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RoleDefine3
        {
            get
            {
                return _RoleDefine3;
            }
            set
            {
                OnRoleDefine3Changing(value);
                ReportPropertyChanging("RoleDefine3");
                _RoleDefine3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RoleDefine3");
                OnRoleDefine3Changed();
            }
        }
        private global::System.String _RoleDefine3;
        partial void OnRoleDefine3Changing(global::System.String value);
        partial void OnRoleDefine3Changed();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="financepersonalModel", Name="user")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class user : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 user 对象。
        /// </summary>
        /// <param name="userId">UserId 属性的初始值。</param>
        public static user Createuser(global::System.Int32 userId)
        {
            user user = new user();
            user.UserId = userId;
            return user;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                if (_UserId != value)
                {
                    OnUserIdChanging(value);
                    ReportPropertyChanging("UserId");
                    _UserId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserId");
                    OnUserIdChanged();
                }
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserPassword
        {
            get
            {
                return _UserPassword;
            }
            set
            {
                OnUserPasswordChanging(value);
                ReportPropertyChanging("UserPassword");
                _UserPassword = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserPassword");
                OnUserPasswordChanged();
            }
        }
        private global::System.String _UserPassword;
        partial void OnUserPasswordChanging(global::System.String value);
        partial void OnUserPasswordChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserEmail
        {
            get
            {
                return _UserEmail;
            }
            set
            {
                OnUserEmailChanging(value);
                ReportPropertyChanging("UserEmail");
                _UserEmail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserEmail");
                OnUserEmailChanged();
            }
        }
        private global::System.String _UserEmail;
        partial void OnUserEmailChanging(global::System.String value);
        partial void OnUserEmailChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Define1
        {
            get
            {
                return _Define1;
            }
            set
            {
                OnDefine1Changing(value);
                ReportPropertyChanging("Define1");
                _Define1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Define1");
                OnDefine1Changed();
            }
        }
        private global::System.String _Define1;
        partial void OnDefine1Changing(global::System.String value);
        partial void OnDefine1Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Define2
        {
            get
            {
                return _Define2;
            }
            set
            {
                OnDefine2Changing(value);
                ReportPropertyChanging("Define2");
                _Define2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Define2");
                OnDefine2Changed();
            }
        }
        private global::System.String _Define2;
        partial void OnDefine2Changing(global::System.String value);
        partial void OnDefine2Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Define3
        {
            get
            {
                return _Define3;
            }
            set
            {
                OnDefine3Changing(value);
                ReportPropertyChanging("Define3");
                _Define3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Define3");
                OnDefine3Changed();
            }
        }
        private global::System.String _Define3;
        partial void OnDefine3Changing(global::System.String value);
        partial void OnDefine3Changed();

        #endregion
    
    }

    #endregion
    
}
